# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_django_app', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='email',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='last',
        ),
    ]
