# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_django_app', '0004_auto_20170201_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='belt_django_app.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
